# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=500)),
                ('geolocation', models.CharField(max_length=200)),
                ('opentime', models.TimeField(blank=True, null=True)),
                ('closetime', models.TimeField(blank=True, null=True)),
                ('category', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('logo', models.CharField(max_length=20)),
                ('btag', models.CharField(max_length=20)),
                ('website', models.CharField(max_length=50)),
            ],
        ),
    ]
