# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createprofile',
            name='logo',
            field=models.FileField(upload_to=''),
        ),
    ]
